sudo: required
services:
    - docker

before_install:
    - docker build -t shriganesh1987/docker-react -f Dockerfile.dev .

script:
    #- docker run shriganesh1987/docker-react npm run test -- --coverage
    - docker run -e CI=true shriganesh1987/docker-react npm run test